mercedes-benz/foss

CODE_OF_CONDUCT.md

Acting on behalf of Daimler TSS GmbH.

Change wording slightly

---

SECURITY.md

As shown on the Github Satellite.

Added security information - As shown on the Github Satellite.

---

CONTRIBUTORS_LICENSE_AGREEMENT.md
README.md

Added CLA and FAQ invitation

---

README.md

Description of Daimler Group Foss projects to give contributors an overview about our foss projects.
Kosmoo and VIS descriptions are still missing and have to be done by the maintainers. 
Fabian Faulhaber <fabian.faulhaber@daimler.com> Daimler AG on behalf of [TSS GmbH](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md).

Describe Daimler Group Foss projects

---

CODE_OF_CONDUCT.md

* updated integrity code url
* disallow discrimination because of illness
Signed-off-By: jonas.von_malottki@daimler.com
Daimler AG acting on behalf of Daimler TSS GmbH
https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

updated integrity url

---

legal_imprint/legal_imprint_entity_template.md

Fabian Faulhaber, fabian.faulhaber@daimler.com, Daimler AG on behalf of Daimler TSS GmbH.

Create a provider information template for legal entities

---

LEGAL_IMPRINT.md

Fabian Faulhaber, fabian.faulhaber@daimler.com, Daimler AG on behalf of Daimler TSS GmbH.
Imprint.

Update Provider information

---

CODE_OF_CONDUCT.md
README.md

* leverage github discussion feature
* link linting for mail
Signed-off-by: Jonas von Malottki <jonas.von_malottki@daimler.com>

change to discussion from issue

---

LEGAL_IMPRINT.md

Fabian Faulhaber fabian.faulhaber@daimler.com, Daimler AG on behalf of Daimler TSS GmbH, legal info/Impressum.

Update url to mbition imprint

---

LEGAL_IMPRINT.md

Isabelle Krautwald took over as CFO on December 1, 2020.

Add Isabelle Krautwald to Daimler TSS

---

PROVIDER_INFORMATION.md

Fabian Faulhaber fabian.faulhaber@daimler.com, Daimler AG on behalf of Daimler TSS GmbH, [Imprint](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md).

Update CEO of protics in provider information

---

PROVIDER_INFORMATION.md

We are required to add Mercedes-Benz Connectivity Services GmbH  Provider Information here.

Added MBCS Provider Information

---

PROVIDER_INFORMATION.md

Fabian Faulhaber fabian.faulhaber@daimler.com, Daimler AG on behalf of Daimler TSS GmbH, Imprint.

Update PROVIDER_INFORMATION.md for Mercedes-Benz Connectivity Services GmbH

---

README.md

Fabian Faulhaber fabian.faulhaber@daimler.com, Daimler AG on behalf of [Daimler TSS GmbH](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md).

Update Foss navigator

---

PROVIDER_INFORMATION.md

Daimler TSS was renamed on 1st April to Mercedes-Benz Tech Innovation GmbH.
Also Daniel Geisel ist the new CEO.

replace Daimler TSS with Mercedes-Benz Tech Innovation GmbH

---

LEGAL_IMPRINT.md
MAINTAINERS.md
PROJECT_CONVENTIONS.md
PROVIDER_INFORMATION.md
README.md
SECURITY.md

Lot's of  changes due to changes of various company names, Imprint, eMail and such

Daimler > Mercedes-Benz

---

CONTRIBUTORS_LICENSE_AGREEMENT.md

This updates the specified email address for mbition contributions from CLA-MBition@daimler.com to cla-mbition@mercedes-benz.com.
Andreas Lauser &lt;<andreas.lauser@mercedes-benz.com>&gt;, on behalf of [MBition GmbH](https://mbition.io/).
[Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)

Correct email address

---

PROVIDER_INFORMATION.md

As we are contributing to Neodash (open source project: neo4j-labs/neodash), requesting our provider information be added to master. Information gathered after coordination with local FOSS Spoc Amit Yadav (MBRDI) - who can be reached at amit.yadav@mercedes-benz.com.
Best Regards
Brahm
Sr. Tech Lead,
Team OTA
MB RD - India

Add MBRDI to Provider Information

---

PROVIDER_INFORMATION.md

Update information about CEO and CTO, and email addresses for contact.

Update MBition management in text files

---

PROVIDER_INFORMATION.md

The information about Mercedes-Benz Tech Motion GmbH were outdated.

Update PROVIDER_INFORMATION.md for MBTM

---

PROVIDER_INFORMATION.md

MBition has a new CFO.   @mbenelli Please also review/confirm.
See: https://mbition.io/imprint/

Update provider information with MBition's new CFO

---

PROVIDER_INFORMATION.md

Added the Mercedes-AMG Provider information based on https://www.mercedes-amg.com/en/provider.

Amg provider info
